spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123
  redis:
    #数据库编号
    database: 0
    host: 150.158.28.238
    port: 6369
    #超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接数，默认8
        max-idle: 200
        #最小空闲连接数，默认0
        min-idle: 5

#mybatis-plus:
#  configuration:
##    mysql语句打印
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always

#swagger3
springfox:
  documentation:
    swagger-ui:
      enabled: true

